[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "promptmin"
version = "1.0.0"
description = "Prompt Minimizer Python wrapper"
requires-python = ">=3.9"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/10fra/promptmin"

[project.scripts]
promptmin-py = "promptmin.cli:main"

[tool.setuptools]
packages = ["promptmin"]
