[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "promptmin"
version = "0.0.0"
description = "Prompt Minimizer Python wrapper"
requires-python = ">=3.9"

[project.scripts]
promptmin-py = "promptmin.cli:main"

[tool.setuptools]
packages = ["promptmin"]
